/***/
import {
  coreServices,
  createExtensionPoint,
} from '@backstage/backend-plugin-api';
import { MigrationEntityV1 } from '@district09/backstage-plugin-migrations-common';
import { catalogServiceRef } from '@backstage/plugin-catalog-node';
import { Entity, stringifyEntityRef } from '@backstage/catalog-model';

/**
 * Node.js library for the migrations plugin.
 *
 * @packageDocumentation
 */
export type CheckResultsDbEntity = {
  id?: number; // id is optional, auto-generated by DB
  checkId: string;
  description?: string;
  result: boolean;
  checked_at?: string; // ISO timestamp
  migrationReference: string;
  componentReference: string;
};

export interface MigrationCheckResult {
  result: boolean;
}

export interface MigrationChecker {
  id: string;
  description: string;

  runCheckForAllRelatedEntities(
    migration: MigrationEntityV1,
  ): Promise<CheckResultsDbEntity[]>;

  // TODO: runEntityChecks(entity: CompoundEntityRef): Promise<void>;
}

export abstract class BaseMigrationChecker implements MigrationChecker {
  abstract id: string;
  abstract description: string;
  protected readonly catalog: typeof catalogServiceRef.T;
  protected readonly auth: typeof coreServices.auth.T;
  protected readonly logger: typeof coreServices.logger.T;

  protected constructor({
    catalog,
    auth,
    logger,
  }: {
    catalog: typeof catalogServiceRef.T;
    auth: typeof coreServices.auth.T;
    logger: typeof coreServices.logger.T;
  }) {
    this.catalog = catalog;
    this.auth = auth;
    this.logger = logger;
  }

  async runCheckForAllRelatedEntities(
    migration: MigrationEntityV1,
  ): Promise<CheckResultsDbEntity[]> {
    const entities = await this.getRelatedEntities(migration);
    const allResults: CheckResultsDbEntity[] = [];
    this.logger.info(
      `Running check '${this.id}' on ${
        entities.length
      } entities related to migration ${stringifyEntityRef(migration)}`,
    );
    for (const e of entities) {
      const result = await this.runCheck(e, migration);
      allResults.push({
        checkId: this.id,
        description: this.description,
        migrationReference: stringifyEntityRef(migration),
        componentReference: stringifyEntityRef(e),
        result: result.result,
      });
    }
    return allResults;
  }

  abstract runCheck(
    entity: Entity,
    migration: MigrationEntityV1,
  ): Promise<MigrationCheckResult>;

  private async getRelatedEntities(
    migration: MigrationEntityV1,
  ): Promise<Entity[]> {
    const entities = await this.catalog.getEntities(
      { filter: migration.spec.entityFilter },
      { credentials: await this.auth.getOwnServiceCredentials() },
    );
    return entities.items;
  }
}

export interface MigrationCheckerExtensionPoint {
  addChecker(checker: MigrationChecker): void;
}

export const migrationCheckRunnerExtensionPoint =
  createExtensionPoint<MigrationCheckerExtensionPoint>({
    id: 'migrations.checkrunners',
  });

export interface CheckerStoreService {
  addChecker(checker: MigrationChecker): void;

  getCheckers(): Map<string, MigrationChecker>;

  getChecker(id: string): MigrationChecker | undefined;
}
