/***/
import {
  coreServices,
  createExtensionPoint,
} from '@backstage/backend-plugin-api';
import { MigrationEntityV1 } from '@district09/backstage-plugin-migrations-common';
import { catalogServiceRef } from '@backstage/plugin-catalog-node';
import { Entity, stringifyEntityRef } from '@backstage/catalog-model';

/**
 * Node.js library for the migrations plugin.
 *
 * @packageDocumentation
 */
export type CheckResultsDbEntity = {
  id?: number; // id is optional, auto-generated by DB
  checkId: string;
  description?: string;
  result: boolean;
  message?: string; // optional human-readable explanation of the check result
  checked_at?: string; // ISO timestamp
  migrationReference: string;
  componentReference: string;
};

export type MigrationRunResultDbEntity = {
  id?: number; // id is optional, auto-generated by DB
  migrationReference: string;
  started_at?: string; // ISO timestamp
  passed_count: number;
  partially_passed_count: number;
  total_count: number;
};

export interface MigrationCheckResult {
  result: boolean;
  /** Optional human-readable explanation of why the check passed or failed. */
  message?: string;
}

export type MigrationCheckResultEmitter = (
  result: MigrationCheckResult & { checkId: string; description?: string },
) => void;

export interface MigrationChecker {
  id: string;
  description: string;

  runCheckForAllRelatedEntities(
    migration: MigrationEntityV1,
  ): Promise<CheckResultsDbEntity[]>;

  runCheckForSingleEntity(
    entity: Entity,
    migration: MigrationEntityV1,
  ): Promise<CheckResultsDbEntity[]>;
}

export abstract class BaseMigrationChecker implements MigrationChecker {
  abstract id: string;
  abstract description: string;
  protected readonly catalog: typeof catalogServiceRef.T;
  protected readonly auth: typeof coreServices.auth.T;
  protected readonly logger: typeof coreServices.logger.T;

  protected constructor({
    catalog,
    auth,
    logger,
  }: {
    catalog: typeof catalogServiceRef.T;
    auth: typeof coreServices.auth.T;
    logger: typeof coreServices.logger.T;
  }) {
    this.catalog = catalog;
    this.auth = auth;
    this.logger = logger;
  }

  async runCheckForAllRelatedEntities(
    migration: MigrationEntityV1,
  ): Promise<CheckResultsDbEntity[]> {
    const entities = await this.getRelatedEntities(migration);
    const allResults: CheckResultsDbEntity[] = [];
    this.logger.info(
      `Running check '${this.id}' on ${
        entities.length
      } entities related to migration ${stringifyEntityRef(migration)}`,
    );
    for (const e of entities) {
      const emit: MigrationCheckResultEmitter = result => {
        allResults.push({
          checkId: result.checkId,
          description: result.description,
          migrationReference: stringifyEntityRef(migration),
          componentReference: stringifyEntityRef(e),
          result: result.result,
          message: result.message,
        });
      };
      await this.runCheck(e, migration, emit);
    }
    return allResults;
  }

  async runCheckForSingleEntity(
    entity: Entity,
    migration: MigrationEntityV1,
  ): Promise<CheckResultsDbEntity[]> {
    const results: CheckResultsDbEntity[] = [];
    this.logger.info(
      `Running check '${this.id}' on entity ${stringifyEntityRef(
        entity,
      )} for migration ${stringifyEntityRef(migration)}`,
    );
    const emit: MigrationCheckResultEmitter = result => {
      results.push({
        checkId: result.checkId,
        description: result.description,
        migrationReference: stringifyEntityRef(migration),
        componentReference: stringifyEntityRef(entity),
        result: result.result,
        message: result.message,
      });
    };
    await this.runCheck(entity, migration, emit);
    return results;
  }

  abstract runCheck(
    entity: Entity,
    migration: MigrationEntityV1,
    emit: MigrationCheckResultEmitter,
  ): Promise<void>;

  private async getRelatedEntities(
    migration: MigrationEntityV1,
  ): Promise<Entity[]> {
    const entities = await this.catalog.getEntities(
      { filter: migration.spec.entityFilter },
      { credentials: await this.auth.getOwnServiceCredentials() },
    );
    return entities.items;
  }
}

export interface MigrationCheckerExtensionPoint {
  addChecker(checker: MigrationChecker): void;
}

export const migrationCheckRunnerExtensionPoint =
  createExtensionPoint<MigrationCheckerExtensionPoint>({
    id: 'migrations.checkrunners',
  });

export interface CheckerStoreService {
  addChecker(checker: MigrationChecker): void;

  getCheckers(): Map<string, MigrationChecker>;

  getChecker(id: string): MigrationChecker | undefined;
}
